# Generated by Django 5.1.6 on 2025-02-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_post_name_post_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publisher',
            new_name='author',
        ),
    ]
