# Generated by Django 5.1.6 on 2025-03-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_userverificationtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userverificationtoken',
            old_name='token',
            new_name='value',
        ),
    ]
