# Generated by Django 5.1.14 on 2025-12-07 22:40

from django.db import migrations


def update_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')

    # Update or create the site with ID = 1
    Site.objects.update_or_create(
        id=1,
        defaults={
            "domain": "urbandictionary.sk",
            "name": "Urban Dictionary",
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        # Replace this with your actual last migration
        ('posts', '0004_rename_downvotes_post_dislike_count_and_more'),

        # Ensure Django's sites migrations run first
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(update_site),
    ]
