# Generated by Django 5.1.14 on 2026-03-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedEmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
