# Generated by Django 5.1.14 on 2026-03-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_blockedemaildomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamRegEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
