# Generated by Django 5.1.14 on 2026-04-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_spamregex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spamregex',
            options={'verbose_name': 'Blocked pattern', 'verbose_name_plural': 'Blocked patterns'},
        ),
        migrations.AddField(
            model_name='spamregex',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
