# Generated by Django 5.1.14 on 2026-04-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_spamregex_options_spamregex_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postunverified',
            name='verification_token',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_example',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='postunverified',
            name='post_example',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='postunverified',
            name='post_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='UserVerificationToken',
        ),
    ]
